MyForum/Models/Subject.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyForum.Models
{
    public class Subject
    {
        public int Id { get; set; }
        [Display(Name = "Название темы")]
        public string SubjectName {get; set;}
       
        [Display(Name = "Содержимое")]
        public string Content { get; set; }

        public DateTime Date { get; set; }

        public string UserId { get; set; }
        public User User { get; set; }

        public List<Message> Messages { get; set; }
        public Subject()
        {
            Messages = new List<Message>();
        }

    }
}

MyForum/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyForum.Models;
using MyForum.ViewModels;

namespace MyForum.Controllers
{
    public class MessageController : Controller
    {
        private UserManager<User> userManager;
        private ApplicationContext ApplicationContext;

        public MessageController(UserManager<User> userManager, ApplicationContext ApplicationContext)
        {
            this.userManager = userManager;
            this.ApplicationContext = ApplicationContext;
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(int subjectId, string userName, string content)
        {
            User user = await userManager.FindByNameAsync(userName);
            Message message = new Message
            {
                SubjectId = subjectId,
                Date = DateTime.Now,
                User = user,
                Content = content,
                UserId = user.Id
            };
            await ApplicationContext.Messages.AddRangeAsync(message);
            await ApplicationContext.SaveChangesAsync();
            MessageViewModel messageViewModel = new MessageViewModel
            {
                Content = message.Content,
                Author = user.UserName,
                Date = message.Date.ToShortDateString()
            };

            return Json(messageViewModel);
        }

        
       
    }
}

MyForum/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyForum.Models;

namespace MyForum.Controllers
{
    public class SubjectController : Controller
    {

        private UserManager<User> userManager;
        private ApplicationContext ApplicationContext;

        public SubjectController(UserManager<User> userManager, ApplicationContext ApplicationContext)
        {
            this.userManager = userManager;
            this.ApplicationContext = ApplicationContext;
        }


        [Authorize]
        public async Task<IActionResult> Create()
        {
            User user = await userManager.FindByNameAsync(User.Identity.Name);
            ViewBag.UserId = user.Id;
            return View();

        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(Subject subject)
        {
            if (ModelState.IsValid)
            {
                subject.Date = DateTime.Now;
                ApplicationContext.Subjects.Add(subject);
                await ApplicationContext.SaveChangesAsync();
            }
            return RedirectToAction("Index", "Subject", new { subjectId = subject.Id });

        }
       

        public IActionResult Index(int subjectId)
        {
            Subject subject = ApplicationContext.Subjects.Include(s => s.User).Include(s=>s.Messages).ThenInclude(m => m.User).FirstOrDefault(s => s.Id == subjectId);
            return View(subject);
        }

        //public IActionResult Subjects()
        //{
        //    List<Subject> subjects = ApplicationContext.Subjects.Include(s => s.User).ToList();

        //    return View();
        //}
        public async Task<IActionResult> Subjects()
        {
            var applicationDbContext = ApplicationContext.Subjects.Include(p => p.User).OrderByDescending(p => p.Date);
            return View(await applicationDbContext.ToListAsync());
        }

        //[HttpPost]
        public IActionResult SubjectSearch(string name)
        {
            var allSubjects = ApplicationContext.Subjects.Where(a => a.SubjectName.Contains(name)).ToList();
            return PartialView(allSubjects);
        }



    }
}

MyForum/Views/Subject/Create.cshtml
@model MyForum.Models.Subject

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Subject</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SubjectName" class="control-label"></label>
                <input asp-for="SubjectName" class="form-control" />
                <span asp-validation-for="SubjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="UserId" class="form-control" value="@ViewBag.UserId" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MyForum/Views/Subject/Index.cshtml
@model MyForum.Models.Subject

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>@Model.User</h4>
\

<h4>Тема:  @Model.SubjectName</h4><br />
<h5>Описание :   @Model.Content</h5>
<h6>@Model.Date</h6>
<div id="com" >
    <table id="messages">
        @foreach (var message in Model.Messages)
        {
            <tr>
                <td style="padding: 7px">
                    @message.User.UserName<br />
                    @message.Date.ToShortDateString()
                </td>
                <td>
                    @message.Content
                </td>
            </tr>

        }
    </table>

</div>
@if (User.Identity.IsAuthenticated)
{

    <div id="postdiv">
        <textarea id="posttext"></textarea>
        <input type="button" onclick="sendComment('@Model.Id', '@User.Identity.Name')" value="Отправить" />
    </div>
}
@section Scripts{
    <script>

        function openCommentForm(subjectId) {
            $('#postdiv' + subjectId).show();
        }

        function sendComment(subjectId, userName) {
            $.ajax({
                url: '@Url.Action("Create", "Message")',
                type: 'POST',
                data: { 'subjectId': subjectId, 'userName': userName, 'content': $('#posttext').val() },
                success: function(data) {
                    //var a = JSON.parse(data);
                    //console.log(a)
                    var str = '<tr><td style="padding: 7px">' + data.author + '<br/>' + data.date + '</td><td>' + data.content + '</td></tr>'
                    console.log(data)
                    $('#messages').append(str);
                },
                error: function() {
                    console.log('Ошибка во время отправки комментария');
                }
            });
        }


    </script>
}

MyForum/Views/Subject/SubjectSearch.cshtml
@model IEnumerable<MyForum.Models.Subject>

  

    <ul>
        @foreach (var item in Model)
        {
            <li>
                <a asp-action="Index" asp-controller="Subject" asp-route-subjectId="@item.Id"> @item.SubjectName</a>
            </li>

        }
    </ul>

MyForum/Views/Subject/Subjects.cshtml
@model IEnumerable<MyForum.Models.Subject>
@{
    ViewData["Title"] = "Subjects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Subjects</h2>

<input type="text" id="name" name="name"/>
<input type="submit" id="submit" name="search" />



@section Scripts{
    <script>

     $(document).ready(function () {
            $('#submit').click(function (e) {
                e.preventDefault();
                var name = $('#name').val();
                searchKey = encodeURIComponent(name);
                $('#results').load('@Url.Action("SubjectSearch", "Subject")?name=' +   name);
            });
        });

</script>
    }

<div  id="results"></div>


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SubjectName)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SubjectName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.UserName)
                </td>
                <td>
                    <a asp-action="Index" asp-controller="Subject" asp-route-subjectId="@item.Id">Посмотреть</a> 

                </td>
            </tr>
        }
    </tbody>
</table>